# Generated by Django 5.1.2 on 2024-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuranceCashflowVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("premium", models.CharField(max_length=200)),
                ("claims", models.CharField(max_length=200)),
                ("acquisition", models.CharField(max_length=200)),
                ("admin", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ReinsuranceCashflowVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("premium", models.CharField(max_length=200)),
                ("claims", models.CharField(max_length=200)),
                ("acquisition", models.CharField(max_length=200)),
                ("admin", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="RunSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PrevRun_Nr", models.IntegerField()),
                ("NBRun_Nr", models.IntegerField()),
                ("Run_Nr", models.IntegerField()),
                ("Run_Description", models.CharField(max_length=200)),
                ("ForwardInterestRatesName_IFstart", models.CharField(max_length=200)),
                ("ForwardInterestRatesName_IFend", models.CharField(max_length=200)),
                ("ForwardInterestRatesName_NB", models.CharField(max_length=200)),
                ("EconomicAssumptionsName", models.CharField(max_length=200)),
                (
                    "RiskAdj",
                    models.CharField(
                        choices=[("Percentage", "Percentage"), ("Formula", "Formula")],
                        max_length=200,
                    ),
                ),
                ("RiskAdjustmentFac", models.FloatField()),
                ("IncurredAcqCotsPeriod", models.FloatField()),
            ],
        ),
    ]
