# Generated by Django 5.1.2 on 2024-10-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("projected_month", models.PositiveIntegerField()),
                ("nominal_forward_rate", models.FloatField()),
                ("real_forward_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("in-force", "In-Force"),
                            ("new_business", "New Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("onerous", "Onerous"),
                            ("non-onerous", "Non-Onerous"),
                            ("remaining", "Remaining"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.PositiveIntegerField()),
                ("PREM_INC", models.FloatField()),
                ("DEATH_OUTGO", models.FloatField()),
                ("DISAB_OUTGO", models.FloatField()),
                ("INIT_EXP", models.FloatField()),
                ("REN_EXP", models.FloatField()),
                ("INIT_COMM", models.FloatField()),
                ("REN_COMM", models.FloatField()),
                ("PHIBEN_OUTGO", models.FloatField()),
                ("PHIBEN_OUTGO_BLL", models.FloatField()),
                ("CR_BEN_OUTGO", models.FloatField()),
                ("RETR_OUTGO", models.FloatField()),
                ("DTH_OUTGO", models.FloatField()),
                ("DREADDIS_OUTGO", models.FloatField()),
                ("TEMPDIS_OUTGO", models.FloatField()),
                ("RIDERC_OUTGO", models.FloatField()),
                ("RISK_ADJ", models.FloatField()),
                ("COVERAGE_UNITS", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Reinsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("in-force", "In-Force"),
                            ("new_business", "New Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("onerous", "Onerous"),
                            ("non-onerous", "Non-Onerous"),
                            ("remaining", "Remaining"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.PositiveIntegerField()),
                ("reins_prem_treaty_out_1", models.FloatField()),
                ("reins_prem_treaty_out_2", models.FloatField()),
                ("reins_prem_treaty_out_3", models.FloatField()),
                ("reins_prem_treaty_out_4", models.FloatField()),
                ("reins_prem_treaty_out_5", models.FloatField()),
                ("reins_prem_treaty_out_6", models.FloatField()),
                ("rpr_prem_out_treaty_out_1", models.FloatField()),
                ("rpr_prem_out_treaty_out_2", models.FloatField()),
                ("rpr_prem_out_treaty_out_3", models.FloatField()),
                ("rpr_prem_out_treaty_out_4", models.FloatField()),
                ("rpr_prem_out_treaty_out_5", models.FloatField()),
                ("rpr_prem_out_treaty_out_6", models.FloatField()),
                ("fr_repayment", models.FloatField()),
                ("fr_clawback", models.FloatField()),
                ("reins_rec_treaty_out_1", models.FloatField()),
                ("reins_rec_treaty_out_2", models.FloatField()),
                ("reins_rec_treaty_out_3", models.FloatField()),
                ("reins_rec_treaty_out_4", models.FloatField()),
                ("reins_rec_treaty_out_5", models.FloatField()),
                ("reins_rec_treaty_out_6", models.FloatField()),
                ("rpr_dth_rec_treaty_out_1", models.FloatField()),
                ("rpr_dth_rec_treaty_out_2", models.FloatField()),
                ("rpr_dth_rec_treaty_out_3", models.FloatField()),
                ("rpr_dth_rec_treaty_out_4", models.FloatField()),
                ("rpr_dth_rec_treaty_out_5", models.FloatField()),
                ("rpr_dth_rec_treaty_out_6", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_1", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_2", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_3", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_4", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_5", models.FloatField()),
                ("rpr_phiben_rec_treaty_out_6", models.FloatField()),
                ("fr_new_finan", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_1", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_2", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_3", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_4", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_5", models.FloatField()),
                ("risk_adj_ri_treaty_out_fr_6", models.FloatField()),
                ("coverage_units_ri_treaty_out_1", models.FloatField()),
                ("coverage_units_ri_treaty_out_2", models.FloatField()),
                ("coverage_units_ri_treaty_out_3", models.FloatField()),
                ("coverage_units_ri_treaty_out_4", models.FloatField()),
                ("coverage_units_ri_treaty_out_5", models.FloatField()),
                ("coverage_units_ri_treaty_out_6", models.FloatField()),
            ],
        ),
    ]
