# Generated by Django 5.1.2 on 2024-10-17 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curves",
            options={"verbose_name": "Curve", "verbose_name_plural": "Curves"},
        ),
    ]
