# Generated by Django 5.1.2 on 2024-10-17 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_curves_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curves",
            options={
                "verbose_name": "Forward Rate",
                "verbose_name_plural": "Forward Rates",
            },
        ),
        migrations.AlterModelOptions(
            name="insurance",
            options={
                "verbose_name": "Insurance Data",
                "verbose_name_plural": "Insurance Data",
            },
        ),
        migrations.AlterModelOptions(
            name="reinsurance",
            options={
                "verbose_name": "Reinsurance Data",
                "verbose_name_plural": "Reinsurance Data",
            },
        ),
    ]
