# Generated by Django 5.1.2 on 2024-10-18 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_portfolio_insurance_portfolio_reinsurance_portfolio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curves",
            options={"verbose_name": "Forward Rate"},
        ),
    ]
