# Generated by Django 5.1.2 on 2024-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_curves_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="time",
            field=models.DateField(),
        ),
    ]
