# Generated by Django 5.1.2 on 2024-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_insurance_time_alter_reinsurance_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="COVERAGE_UNITS",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="CR_BEN_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="DEATH_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="DISAB_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="DREADDIS_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="DTH_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="INIT_COMM",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="INIT_EXP",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="PHIBEN_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="PHIBEN_OUTGO_BLL",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="PREM_INC",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="REN_COMM",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="REN_EXP",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="RETR_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="RIDERC_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="RISK_ADJ",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="TEMPDIS_OUTGO",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="coverage_units_ri_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="fr_clawback",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="fr_new_finan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="fr_repayment",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_prem_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="reins_rec_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="risk_adj_ri_treaty_out_fr_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_dth_rec_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_phiben_rec_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="rpr_prem_out_treaty_out_6",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
