# Generated by Django 5.1.2 on 2024-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_insurance_coverage_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="time",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
