# Generated by Django 5.1.2 on 2024-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_insurance_time_alter_reinsurance_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="group",
            field=models.CharField(
                choices=[
                    ("onerous", "Onerous"),
                    ("non-onerous", "Non-Onerous"),
                    ("remaining", "Remaining"),
                    ("odd", "ODD"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reinsurance",
            name="group",
            field=models.CharField(
                choices=[
                    ("onerous", "Onerous"),
                    ("non-onerous", "Non-Onerous"),
                    ("remaining", "Remaining"),
                    ("odd", "ODD"),
                ],
                max_length=20,
            ),
        ),
    ]
