# Generated by Django 5.1.2 on 2024-10-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_forward_rate_files_insurance_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forward_rate_files",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Calculations/Rscript/Assumptions/TABLES/Curves/Base/Csv/",
            ),
        ),
        migrations.AlterField(
            model_name="insurance_files",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Calculations/Rscript/Inputs/Base/User_Inputs/FCFs/",
            ),
        ),
    ]
