# Generated by Django 5.1.2 on 2024-10-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_forward_rate_files_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forward_rate_files",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Rscript/Assumptions/TABLES/Curves/Base/Csv/",
            ),
        ),
        migrations.AlterField(
            model_name="insurance_files",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="Rscript/Inputs/Base/User_Inputs/FCFs/"
            ),
        ),
    ]
