# Generated by Django 5.0.6 on 2024-10-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "subledger_file",
                    models.FileField(upload_to="financial_statements/subledgers/"),
                ),
                (
                    "trial_balance_file",
                    models.FileField(upload_to="financial_statements/trial_balances/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
