# Generated by Django 5.0.6 on 2024-10-17 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Fianancial_Statements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialstatement",
            name="trial_balance_file",
        ),
    ]
