# Generated by Django 5.0.6 on 2024-10-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fianancial_Statements", "0002_remove_financialstatement_trial_balance_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "trial_balance_file",
                    models.FileField(upload_to="financial_statements/trial_balances/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
