# Generated by Django 5.0.6 on 2024-10-17 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Fianancial_Statements", "0003_trialbalance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FinancialStatement",
            new_name="Subledger",
        ),
    ]
