# Generated by Django 5.0.6 on 2024-10-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "clearview_audit_file",
                    models.FileField(upload_to="analytics/reports/clearview_audit/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PowerBi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "kpi_power_bi_file",
                    models.FileField(upload_to="analytics/reports/kpi_power_bi/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AnalyticsReport",
        ),
    ]
