# Generated by Django 5.0.6 on 2024-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calculations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pam1000",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "upload_file",
                    models.FileField(blank=True, null=True, upload_to="pam1000_files/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="calculationresult",
            name="model_run",
        ),
        migrations.DeleteModel(
            name="FinancialScenario",
        ),
        migrations.DeleteModel(
            name="CalculationResult",
        ),
    ]
