# Generated by Django 5.0.6 on 2024-10-18 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Calculations", "0002_pam1000_remove_calculationresult_model_run_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetsetup",
            options={"verbose_name_plural": "BudgetSetup"},
        ),
        migrations.AlterModelOptions(
            name="modelrun",
            options={"verbose_name_plural": "ModelRun"},
        ),
        migrations.AlterModelOptions(
            name="pam1000",
            options={"verbose_name_plural": "Pam1000"},
        ),
        migrations.AlterModelOptions(
            name="runlog",
            options={"verbose_name_plural": "RunLog"},
        ),
    ]
