# Generated by Django 5.1.2 on 2024-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calculations", "0004_modelrun_nbrun_nr_modelrun_prevrun_nr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashflowVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("premiums", models.CharField(max_length=255)),
                ("claims", models.CharField(max_length=255)),
                ("admin", models.CharField(max_length=255)),
                ("acquisitions", models.CharField(max_length=255)),
            ],
        ),
    ]
