# Generated by Django 5.1.2 on 2024-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calculations", "0005_cashflowvariables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowvariables",
            name="acquisitions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cashflowvariables",
            name="admin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cashflowvariables",
            name="claims",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cashflowvariables",
            name="premiums",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
