# Generated by Django 5.2 on 2025-05-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date_previous', models.DateField()),
                ('reporting_date_current', models.DateField()),
                ('reporting_currency', models.CharField(max_length=10)),
                ('insurance_contracts', models.BooleanField()),
                ('reinsurance_contracts', models.BooleanField()),
                ('insurance_new_business', models.BooleanField()),
                ('reinsurance_new_business', models.BooleanField()),
                ('foreign_currency_needed', models.BooleanField()),
                ('linked_cashflows', models.BooleanField()),
                ('dependent_cashflows', models.BooleanField()),
                ('loss_components', models.BooleanField()),
                ('gic_external_model', models.BooleanField()),
                ('interest_rate_effects', models.CharField(max_length=50)),
                ('disaggregate_change', models.BooleanField()),
                ('simplify_ra', models.BooleanField()),
                ('discount_csm', models.BooleanField()),
                ('discount_acquisition_flows', models.BooleanField()),
                ('discount_amortisation_pattern', models.CharField(blank=True, max_length=100)),
                ('granular_yield', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SetupInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rfr_pc', models.FileField(upload_to='ecl_calculations/rfr_pc/')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_inputs', to='homepage.setup')),
            ],
        ),
    ]
