# Generated by Django 5.2 on 2025-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_setup_setupinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('yield_curve', 'Yield Curve'), ('exchange_rate', 'Exchange Rate'), ('i_groups', 'I Groups'), ('i_equity', 'I Equity'), ('i_new_gen', 'I NEW GEN'), ('i_new_cfs', 'I NEW CFs'), ('i_if_gen', 'I IF GEN'), ('i_if_fcfs', 'I IF FCFs'), ('i_if_patterns', 'I IF PATTERNS'), ('r_groups', 'R Groups'), ('r_equity', 'R EQUITY'), ('r_i_mapping', 'R I Mapping'), ('r_new_gen', 'R NEW GEN'), ('r_new_cfs', 'R NEW CFs'), ('r_new_lr', 'R NEW LR'), ('r_i_new_cfs', 'R I NEW CFs'), ('r_if_gen', 'R IF GEN'), ('r_if_fcfs', 'R IF FCFs'), ('r_if_patterns', 'R IF Patterns'), ('r_i_if_fcfs', 'R I IF FCFs'), ('r_if_gen_lr', 'R IF GEN LR')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/input_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
