# Generated by Django 5.2 on 2025-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_inputupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputupload',
            name='category',
            field=models.CharField(blank=True, choices=[('core', 'Core Inputs'), ('insurance', 'Insurance'), ('reinsurance', 'Reinsurance')], max_length=50, null=True),
        ),
    ]
