# Generated by Django 5.2 on 2025-05-28 10:39

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_inputupload_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputupload',
            name='file',
            field=models.FileField(upload_to=homepage.models.upload_to_by_category),
        ),
    ]
