# Generated by Django 5.0.6 on 2024-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetORSA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "financial_orsa_file",
                    models.FileField(upload_to="budget_orsa/financial_orsa/"),
                ),
                (
                    "actuarial_report_file",
                    models.FileField(upload_to="budget_orsa/actuarial_reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
