# Generated by Django 5.0.6 on 2024-10-17 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Budget_ORSA", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetorsa",
            name="actuarial_report_file",
        ),
    ]
