# Generated by Django 5.0.6 on 2024-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget_ORSA", "0002_remove_budgetorsa_actuarial_report_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActuarialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "actuarial_report_file",
                    models.FileField(upload_to="budget_orsa/actuarial_reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="BudgetORSA",
            new_name="ORSADisclosures",
        ),
    ]
