# Generated by Django 5.1.2 on 2024-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget_ORSA", "0003_actuarialreport_rename_budgetorsa_orsadisclosures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ORSA_Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Stress", models.CharField(max_length=255)),
                ("Value", models.CharField(max_length=255)),
                ("Description", models.CharField(max_length=255)),
            ],
        ),
    ]
